[package]
name = "kursor"
version = "0.1.0"
edition = "2021"

[dependencies]
device_query = "2.1.0"
once_cell = "1.20.2"
rdev = { version = "0.5.3", features = ["unstable_grab"] }
tokio = { version = "1.41.0", features = ["rt-multi-thread", "sync", "time"] }
